### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by carlomanf** [carlomanf/wp-funnel-manager#19]
This is an overview of the new features to be started in 2023 in the order they are planned to be addressed. Some have their own issues already, while others can be created later.

- [ ] #15 is the first to be addressed.
- [ ] #18 will follow.
- [ ] Next, it would make a lot of sense to add a "conversion tracking" feature for measuring the percentage of traffic that flows from one funnel step to the next, assigning monetary values to steps and extrapolating accordingly.
- [ ] A possible feature is to enable funnel structures to be created out of posts, pages or other post types, rather than using the built-in post types that the plugin provides. Funnels created this way can still use the #18 and "conversion tracking" features, although they can't use the #15 and #17 features, which is why this feature makes more sense to be added later.
- [ ] Finally, it would be great to be able to edit an entire funnel (i.e. switch between and re-arrange steps) within a single block editor screen, without needing to use the post type screen. This feature is left for last because the front-end work will probably make it the most difficult to implement.

**Comment by carlomanf** [comment]
> Next, it would make a lot of sense to add a "conversion tracking" feature for measuring the percentage of traffic that flows from one funnel step to the next, assigning monetary values to steps and extrapolating accordingly.

I believe there is a lot of potential for this feature and it will be a good candidate for v1.5.0 alongside #18. I will create a full issue for this probably once #18 is implemented, as it will be clearer at that point what sub-tasks it will involve.
